### ISSUE TITLE
trasferable object

### ISSUE THREAD

**Issue by francescoagati** [calvinmetcalf/catiline#126]
Hi,
Catiline support transfarable object?

**Comment by calvinmetcalf** [comment]
yes, just pass an array of buffers as the second argument when you send data

**Comment by francescoagati** [comment]
Bit it works only with postmessage or also with proxy methods?
Il 06/mar/2014 20:59 "Calvin Metcalf" notifications@github.com ha scritto:

**Comment by calvinmetcalf** [comment]
both
