### ISSUE TITLE
Unable to throw error in success, error callbacks

### ISSUE THREAD

**Issue by napoleond** [calvinmetcalf/catiline#128]
Errors in the callbacks are suppressed by the try/catch block in `execute()`, i.e.:

``` javascript
worker.testFunc(args).then(
  function (returnValue) {
    if (returnValue == bad) {
      throw new Error("Return value is bad!"); //this error would get suppressed
    }
  },
  function (errMsg) {
    throw new Error(errMsg); //this error would also get suppressed
  }
);
```

It's possible to make the errors throw by escaping the context, i.e.:

``` javascript
worker.testFunc(args).then(
  function (returnValue) {
    if (returnValue == bad) {
      setTimeout(function(){
        throw new Error("Return value is bad!"); //this error would get thrown
      },0);
    }
  },
  function (errMsg) {
    setTimeout(function(){
      throw new Error(errMsg); //this error would also get thrown
    },0);
  }
);
```

I am planning to put together a PR that would use `nextTick` in `execute` to fix this--is that the right approach or am I barking up the wrong tree entirely?

**Comment by calvinmetcalf** [comment]
so that is a feature of promises, what you can do is 

```
worker.testFunc(args).then(
  function (returnValue) {
    if (returnValue == bad) {
      throw new Error("Return value is bad!"); //this error would get suppressed
    }
  }).then(null, function(err) {
   //catch any errors from either the worker or the callback
});
```

this is inline with the [promise a plus spec](http://promisesaplus.com/) which is what is in chrome and firefox and ES6 (though catiline isn't totally compliant at the moment with version 1.1 of the spec, it is compliant with version 1.0)

**Comment by napoleond** [comment]
[Oops, deleting my previous comment it didn't make sense.]

Thanks for your help!
