### ISSUE TITLE
Does not work with EmberJs

### ISSUE THREAD

**Issue by angusmcleod** [calvinmetcalf/catiline#137]
Throws this error.
`
Uncaught Error: an unsupported module was defined, expected `define(name, deps, module)` instead got: `1` arguments to define
`

The issue Ember has with the form of module use is described here: https://github.com/ngot/devicejs/issues/7

**Comment by calvinmetcalf** [comment]
you should use [the shim build](https://github.com/ember-cli/loader.js/pull/53), but this is more of an issue with ember breaking stuff
