### ISSUE TITLE
Strange performance degradation in Chrome

### ISSUE THREAD

**Issue by aparshin** [calvinmetcalf/catiline#28]
Here is the test case: http://jsfiddle.net/QHz2A/1/

There is rather resource-demanding worker that is called 20 times with the same parameters. Evaluation time of each call is printed to console.

Here is the typical output in Win7 Chrome 26.0.1410.43:

`281, 311, 287, 262, 258, 269, 260, 264, 265, 282, 299, 1910, 2019, 1951, 1914, 1905, 1894, 1908, 1898, 1894`

Note, that last 9 calls are significantly longer than first 11.

There are no such effect in FireFox (I can't check other browsers right now). And I've tried to use native API with `postMessage()` - everything works ok.

**Comment by calvinmetcalf** [comment]
I'm seeing a hangup on the 11th invocation but not for the other 19 http://jsfiddle.net/QHz2A/2/
though I updated it to run in 40 times and I'm also seeing it on the 22 and 33 time meaning it's exactly every 11 invocations, this smells like garbage collection. Once I added in a typed array I did start seeing what you were talking about http://jsfiddle.net/QHz2A/6/

I bet it has to do with creating a typed array inside a closure,

**Comment by calvinmetcalf** [comment]
post message has the same problem if its inside a closure http://jsfiddle.net/QHz2A/7/

**Comment by aparshin** [comment]
> post message has the same problem if its inside a closure http://jsfiddle.net/QHz2A/7/

This example works good for me (in Chrome)!

**Comment by calvinmetcalf** [comment]
I think that this is slightly more complicated then we thought if using the same version of chrome but me in Ubuntu and you on windows have different settings that cause the issue, I'm going to have to in a bit more on this.

**Comment by calvinmetcalf** [comment]
I made some updates, you still seeing this issue? http://jsfiddle.net/QHz2A/11/

**Comment by calvinmetcalf** [comment]
Haven't had this problem in a while, closing.
