### ISSUE TITLE
Browsers support in Windows

### ISSUE THREAD

**Issue by aparshin** [calvinmetcalf/catiline#29]
Checked http://calvinmetcalf.github.io/leaflet-fractal with different browsers at Windows 7:
- FF, Chrome - works without errors!
- Opera 12.14 - `Unhandled Error: Cannot convert 's.URL' to object`
- IE10 - `SCRIPT5022: SecurityError communist.js, line 113 char 3`
- Safari 5.1.7 - `TypeError: 'undefined' is not an object (evaluating 'c.URL.createObjectURL') line 113`.

**Comment by calvinmetcalf** [comment]
yeah the IE 10 one is a known issue in IE, there is a shim I can activate.  

Opera and Safari <6 both don't support Blob URLs

**Comment by calvinmetcalf** [comment]
should be fixed by #30
