### ISSUE TITLE
README.md has important notice that is hard to understand

### ISSUE THREAD

**Issue by Fresheyeball** [calvinmetcalf/catiline#63]
"Important: you're going to want to it yourself, on the same domain as your page, if you can't or need to bundle it and still want it to work on IE10, Opera, and Safari. You need to host the file "SHIM_WORKER.js" on the same domain as the html file and set the path to it in a global variable SHIM_WORKER_PATH before you load this script."

I'm sorry but I have no idea when to host `SHIM_WORKER.js` and when not to from the above statement. This uncertainty fills me with greater fear than I once had for west Berlin. Please clarify kind comrade.

**Comment by calvinmetcalf** [comment]
my bad don't know how that got so mangled
