### ISSUE TITLE
Explain differences with Parallel.js in the Readme

### ISSUE THREAD

**Issue by mourner** [calvinmetcalf/catiline#94]
There's a more popular library with a similar premise — Parallel.js.
https://github.com/adambom/parallel.js

It would be nice if the Readme mentioned the library and the main differences of Communist compared to it.

**Comment by calvinmetcalf** [comment]
I don't want to be too negative about Parallel but I can move the reference to it from the API page where I put it by accident back to the README page and include a link to this https://gist.github.com/calvinmetcalf/6050205

**Comment by mourner** [comment]
Seems like a good explanation, thanks.
